# Generated by Django 6.0.2 on 2026-03-02 06:00

import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations

import events.models.event


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="weather_data",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                schema=events.models.event.WeatherData,
            ),
        ),
    ]
