# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "weather.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rweather.proto"I\n\x0eWeatherRequest\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x12\n\nstart_date\x18\x03 \x01(\t"t\n\x0fWeatherResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08pressure\x18\x02 \x01(\x02\x12\x11\n\twindSpeed\x18\x03 \x01(\x02\x12\x15\n\rwindDirection\x18\x04 \x01(\t\x12\x10\n\x08humidity\x18\x05 \x01(\x02\x32G\n\x0eWeatherService\x12\x35\n\x0eGetWeatherData\x12\x0f.WeatherRequest\x1a\x10.WeatherResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "weather_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_WEATHERREQUEST"]._serialized_start = 17
    _globals["_WEATHERREQUEST"]._serialized_end = 90
    _globals["_WEATHERRESPONSE"]._serialized_start = 92
    _globals["_WEATHERRESPONSE"]._serialized_end = 208
    _globals["_WEATHERSERVICE"]._serialized_start = 210
    _globals["_WEATHERSERVICE"]._serialized_end = 281
# @@protoc_insertion_point(module_scope)
